#fallback
error.internal=حدث خطأ أثناء معالجة الطلب
error.unexpected=حدث خطأ غير متوقع
error.validation=يوجد خطأ في البيانات المدخلة
general.created.successfully=تم الإنشاء بنجاح
general.updated.successfully=تم التحديث بنجاح
general.deleted.successfully=تم الحذف بنجاح
general.fetched.successfully=تم استرجاع البيانات بنجاح