# JWT / Security Errors

security.user.not.found=المستخدم غير موجود

security.jwt.subject.invalid=رمز المصادقة لا يخص هذا المستخدم
security.jwt.expired=انتهت صلاحية رمز المصادقة
security.jwt.malformed=تنسيق رمز المصادقة غير صحيح
security.jwt.invalid=رمز المصادقة غير صالح