# JWT / Security Errors

security.user.not.found=???????? ??? ?????

security.jwt.subject.invalid=????? ???????? ???? ?????? ??? ????
security.jwt.expired=????? ?????? ??????
security.jwt.malformed=???? ?????? ??? ?????
security.jwt.invalid=?????? ??? ????